//------------------------------------------------------------------------------
// <auto-generated>
//     This code was generated by a tool.
//     Runtime Version:4.0.30319.42000
//
//     Changes to this file may cause incorrect behavior and will be lost if
//     the code is regenerated.
// </auto-generated>
//------------------------------------------------------------------------------

namespace VamoPlay.Application.Shared.Resources {
    using System;
    
    
    /// <summary>
    ///   A strongly-typed resource class, for looking up localized strings, etc.
    /// </summary>
    // This class was auto-generated by the StronglyTypedResourceBuilder
    // class via a tool like ResGen or Visual Studio.
    // To add or remove a member, edit your .ResX file then rerun ResGen
    // with the /str option, or rebuild your VS project.
    [global::System.CodeDom.Compiler.GeneratedCodeAttribute("System.Resources.Tools.StronglyTypedResourceBuilder", "17.0.0.0")]
    [global::System.Diagnostics.DebuggerNonUserCodeAttribute()]
    [global::System.Runtime.CompilerServices.CompilerGeneratedAttribute()]
    internal class Resource {
        
        private static global::System.Resources.ResourceManager resourceMan;
        
        private static global::System.Globalization.CultureInfo resourceCulture;
        
        [global::System.Diagnostics.CodeAnalysis.SuppressMessageAttribute("Microsoft.Performance", "CA1811:AvoidUncalledPrivateCode")]
        internal Resource() {
        }
        
        /// <summary>
        ///   Returns the cached ResourceManager instance used by this class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Resources.ResourceManager ResourceManager {
            get {
                if (object.ReferenceEquals(resourceMan, null)) {
                    global::System.Resources.ResourceManager temp = new global::System.Resources.ResourceManager("VamoPlay.Application.Shared.Resources.Resource", typeof(Resource).Assembly);
                    resourceMan = temp;
                }
                return resourceMan;
            }
        }
        
        /// <summary>
        ///   Overrides the current thread's CurrentUICulture property for all
        ///   resource lookups using this strongly typed resource class.
        /// </summary>
        [global::System.ComponentModel.EditorBrowsableAttribute(global::System.ComponentModel.EditorBrowsableState.Advanced)]
        internal static global::System.Globalization.CultureInfo Culture {
            get {
                return resourceCulture;
            }
            set {
                resourceCulture = value;
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail.
        /// </summary>
        internal static string email {
            get {
                return ResourceManager.GetString("email", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail já registrado..
        /// </summary>
        internal static string email_already__registered {
            get {
                return ResourceManager.GetString("email_already _registered", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail já está em uso..
        /// </summary>
        internal static string email_already_used {
            get {
                return ResourceManager.GetString("email_already_used", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Erro ao tentar enviar e-mail. Por favor, verifique se as configurações de e-mail estão preenchidas corretamente..
        /// </summary>
        internal static string email_config_invalid {
            get {
                return ResourceManager.GetString("email_config_invalid", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configurações de e-mail não encontradas..
        /// </summary>
        internal static string email_config_not_found {
            get {
                return ResourceManager.GetString("email_config_not_found", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Configuração de Email.
        /// </summary>
        internal static string email_configuration {
            get {
                return ResourceManager.GetString("email_configuration", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Recuperação de Senha.
        /// </summary>
        internal static string email_forgot_password {
            get {
                return ResourceManager.GetString("email_forgot_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail obrigatório..
        /// </summary>
        internal static string email_is_required {
            get {
                return ResourceManager.GetString("email_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to O e-mail deve ter no máximo {0} caracteres..
        /// </summary>
        internal static string email_max_length {
            get {
                return ResourceManager.GetString("email_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail Teste.
        /// </summary>
        internal static string email_test {
            get {
                return ResourceManager.GetString("email_test", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail com formato inválido, somente letras (a - z), números (0 - 9) e pontos (.) são permitidos..
        /// </summary>
        internal static string invalid_email_format {
            get {
                return ResourceManager.GetString("invalid_email_format", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to E-mail ou senha inválidos.
        /// </summary>
        internal static string invalid_email_or_password {
            get {
                return ResourceManager.GetString("invalid_email_or_password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha.
        /// </summary>
        internal static string password {
            get {
                return ResourceManager.GetString("password", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Senha obrigatória..
        /// </summary>
        internal static string password_is_required {
            get {
                return ResourceManager.GetString("password_is_required", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to A senha deve ter no máximo {0} caracteres..
        /// </summary>
        internal static string password_max_length {
            get {
                return ResourceManager.GetString("password_max_length", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to As senhas não são iguais..
        /// </summary>
        internal static string passwords_not_match {
            get {
                return ResourceManager.GetString("passwords_not_match", resourceCulture);
            }
        }
        
        /// <summary>
        ///   Looks up a localized string similar to Seu usuário foi desativado. Contate um administrador para verificar o status..
        /// </summary>
        internal static string user_disabled {
            get {
                return ResourceManager.GetString("user_disabled", resourceCulture);
            }
        }
    }
}
